const jsonResponse = [ { created_at: 'Thu Jul 19 22:35:59 +0000 2018',
    id: 1020074803565215700,
    id_str: '1020074803565215744',
    text: 'best of luck https://t.co/omb64m5sPL',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 16877374,
       id_str: '16877374',
       name: 'Matt Novak',
       screen_name: 'paleofuture',
       location: 'Man without a country',
       description: 'Writes the Paleofuture blog for @Gizmodo',
       url: 'https://t.co/kdMVtM3j0X',
       entities: [Object],
       protected: false,
       followers_count: 24115,
       friends_count: 2223,
       listed_count: 1358,
       created_at: 'Mon Oct 20 23:44:16 +0000 2008',
       favourites_count: 9993,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 58943,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '131516',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/993928221115670528/lb2GYI6O_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/993928221115670528/lb2GYI6O_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/16877374/1348212262',
       profile_link_color: '009999',
       profile_sidebar_border_color: 'EEEEEE',
       profile_sidebar_fill_color: 'EFEFEF',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 1020073900942782500,
    quoted_status_id_str: '1020073900942782464',
    quoted_status:
     { created_at: 'Thu Jul 19 22:32:24 +0000 2018',
       id: 1020073900942782500,
       id_str: '1020073900942782464',
       text: 'Justice Dept. plans to alert public to foreign attempts to subvert U.S. democracy in effort to foil Russian \'influe… https://t.co/1VbdrbXzIh',
       truncated: true,
       entities: [Object],
       source: '<a href="http://www.washingtonpost.com" rel="nofollow">MainRevere</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 108,
       favorite_count: 169,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       possibly_sensitive_appealable: false,
       lang: 'en' },
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: 'en' },
  { created_at: 'Thu Jul 19 22:31:09 +0000 2018',
    id: 1020073586038624300,
    id_str: '1020073586038624256',
    text: 'Using advanced algorithms, a team of scientists found never-before-detected, fine-grained structures in the Sun’s m… https://t.co/caNV40uEZm',
    truncated: true,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
    source: '<a href="https://www.sprinklr.com" rel="nofollow">Sprinklr</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 11348282,
       id_str: '11348282',
       name: 'NASA',
       screen_name: 'NASA',
       location: '',
       description: 'Explore the universe and discover our home planet with @NASA. We usually post in EST (UTC-5)',
       url: 'https://t.co/TcEE6NS8nD',
       entities: [Object],
       protected: false,
       followers_count: 29290326,
       friends_count: 286,
       listed_count: 91520,
       created_at: 'Wed Dec 19 20:20:32 +0000 2007',
       favourites_count: 3626,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: true,
       statuses_count: 52474,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '000000',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/188302352/nasalogo_twitter_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/188302352/nasalogo_twitter_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/11348282/1532008552',
       profile_link_color: '205BA7',
       profile_sidebar_border_color: '000000',
       profile_sidebar_fill_color: 'F3F2F2',
       profile_text_color: '000000',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'regular' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 89,
    favorite_count: 306,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: 'en' },
  { created_at: 'Thu Jul 19 22:31:05 +0000 2018',
    id: 1020073569294823400,
    id_str: '1020073569294823425',
    text: '“We are witnessing nothing less than the breakdown of American foreign policy.” https://t.co/CiHFWIGmlb',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 16877374,
       id_str: '16877374',
       name: 'Matt Novak',
       screen_name: 'paleofuture',
       location: 'Man without a country',
       description: 'Writes the Paleofuture blog for @Gizmodo',
       url: 'https://t.co/kdMVtM3j0X',
       entities: [Object],
       protected: false,
       followers_count: 24115,
       friends_count: 2223,
       listed_count: 1358,
       created_at: 'Mon Oct 20 23:44:16 +0000 2008',
       favourites_count: 9993,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 58943,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '131516',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/993928221115670528/lb2GYI6O_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/993928221115670528/lb2GYI6O_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/16877374/1348212262',
       profile_link_color: '009999',
       profile_sidebar_border_color: 'EEEEEE',
       profile_sidebar_fill_color: 'EFEFEF',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: 'en' },
  { created_at: 'Thu Jul 19 22:29:33 +0000 2018',
    id: 1020073183364419600,
    id_str: '1020073183364419585',
    text: 'The 2012 West Coast Cypher with Snoop Dogg, Kendrick Lamar, Xzibit, YG, Kurupt, E-40, and DJ Quik. https://t.co/x5aXmrSp8p',
    truncated: false,
    entities:
     { hashtags: [],
       symbols: [],
       user_mentions: [],
       urls: [],
       media: [Array] },
    extended_entities: { media: [Array] },
    source: '<a href="https://ads.twitter.com" rel="nofollow">Twitter Ads</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 834095274,
       id_str: '834095274',
       name: 'Only Hip Hop Facts',
       screen_name: 'OnlyHipHopFacts',
       location: 'New York, NY',
       description: 'info@OnlyHHF.com   |   by: @bargathi',
       url: null,
       entities: [Object],
       protected: false,
       followers_count: 428571,
       friends_count: 831,
       listed_count: 1869,
       created_at: 'Wed Sep 19 20:42:29 +0000 2012',
       favourites_count: 1002,
       utc_offset: null,
       time_zone: null,
       geo_enabled: true,
       verified: false,
       statuses_count: 28614,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '0099B9',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme4/bg.gif',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme4/bg.gif',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/429508172730998786/T6o94fTE_normal.png',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/429508172730998786/T6o94fTE_normal.png',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/834095274/1460675697',
       profile_link_color: '0099B9',
       profile_sidebar_border_color: 'FFFFFF',
       profile_sidebar_fill_color: '95E8EC',
       profile_text_color: '3C3940',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'regular' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 127,
    favorite_count: 228,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: 'en' },
  { created_at: 'Thu Jul 19 22:27:03 +0000 2018',
    id: 1020072553388347400,
    id_str: '1020072553388347392',
    text: 'I\'ve just got a new #fan! Get access to my unseen and exclusive content at https://t.co/W3eNuVEXfD',
    truncated: false,
    entities:
     { hashtags: [Array],
       symbols: [],
       user_mentions: [],
       urls: [Array] },
    source: '<a href="https://onlyfans.com/" rel="nofollow">OnlyFans</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 166103014,
       id_str: '166103014',
       name: 'Bryan Silva GRATATA🦁',
       screen_name: 'OutterSpaceSWAG',
       location: 'Virginia USA',
       description: 'Instagram: imBryanSilva 👻 Snap: BryanSilva69💥Be the first to see, unseen videos and images of me on my Onlyfans account. +18 🔞🔞 https://t.co/VxNGv8sRUE 🔞🔞',
       url: 'https://t.co/tqIrSum76g',
       entities: [Object],
       protected: false,
       followers_count: 42991,
       friends_count: 17,
       listed_count: 123,
       created_at: 'Tue Jul 13 09:53:10 +0000 2010',
       favourites_count: 2308,
       utc_offset: null,
       time_zone: null,
       geo_enabled: true,
       verified: true,
       statuses_count: 4217,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'ACDED6',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/1019118215836905472/f0FPRynw_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/1019118215836905472/f0FPRynw_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/166103014/1527451825',
       profile_link_color: '038543',
       profile_sidebar_border_color: '000000',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'regular' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 4,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: 'en' },
  { created_at: 'Thu Jul 19 22:23:53 +0000 2018',
    id: 1020071756717994000,
    id_str: '1020071756717993985',
    text: 'Any suggested Restaurants? Tweet away now...... https://t.co/0JYniKtrGu',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 110365072,
       id_str: '110365072',
       name: 'Gordon Ramsay',
       screen_name: 'GordonRamsay',
       location: '',
       description: 'Catch a full night of me on Wednesday\'s ! It all starts with #MasterChef at 8/7c followed by #24HoursFOX on @FOXTV !',
       url: 'https://t.co/2fZDEDU9s9',
       entities: [Object],
       protected: false,
       followers_count: 6820635,
       friends_count: 35169,
       listed_count: 14824,
       created_at: 'Mon Feb 01 08:31:59 +0000 2010',
       favourites_count: 296,
       utc_offset: null,
       time_zone: null,
       geo_enabled: true,
       verified: true,
       statuses_count: 20987,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'C0DEED',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/957485325793730561/FyWB3Ifi_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/957485325793730561/FyWB3Ifi_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/110365072/1528952690',
       profile_link_color: '19889C',
       profile_sidebar_border_color: 'C0DEED',
       profile_sidebar_fill_color: 'DDEEF6',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 1020070499601338400,
    quoted_status_id_str: '1020070499601338369',
    quoted_status:
     { created_at: 'Thu Jul 19 22:18:53 +0000 2018',
       id: 1020070499601338400,
       id_str: '1020070499601338369',
       text: '@Channel4 Please commission this with UK restaurants @GordonRamsay',
       truncated: false,
       entities: [Object],
       source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       in_reply_to_status_id: 1020059640531378200,
       in_reply_to_status_id_str: '1020059640531378176',
       in_reply_to_user_id: 183585551,
       in_reply_to_user_id_str: '183585551',
       in_reply_to_screen_name: 'Channel4',
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 0,
       favorite_count: 3,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    retweet_count: 12,
    favorite_count: 176,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: 'en' },
  { created_at: 'Thu Jul 19 22:18:10 +0000 2018',
    id: 1020070318562578400,
    id_str: '1020070318562578432',
    text: 'The world slowly becomes more futuristic',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
    source: '<a href="http://www.davidoreilly.com/" rel="nofollow">Free Facts</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 632281318,
       id_str: '632281318',
       name: 'ＦＲＥＥ_ＦＡＣＴＳ!  🏳️‍🌈 follow for a chance to follow',
       screen_name: 'free_facts',
       location: 'VISA 6127 7433 7810 8900 11/17',
       description: 'New Facts Regualrly 💫 24 / 365 🆒 #Inspring. Makes you think!!! 🤔💭 #woke 100% original new & #free /true #facts, realiable source✨#Verified accunt 🌈',
       url: 'https://t.co/nJClk18FKi',
       entities: [Object],
       protected: false,
       followers_count: 69556,
       friends_count: 0,
       listed_count: 378,
       created_at: 'Tue Jul 10 20:13:12 +0000 2012',
       favourites_count: 7,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 4484,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: 'B8B8B8',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme13/bg.gif',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme13/bg.gif',
       profile_background_tile: false,
       profile_image_url: 'http://pbs.twimg.com/profile_images/818306483494342659/PrpnH9hO_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/818306483494342659/PrpnH9hO_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/632281318/1483934464',
       profile_link_color: '3300FF',
       profile_sidebar_border_color: 'EEEEEE',
       profile_sidebar_fill_color: 'FFFFFF',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 2,
    favorite_count: 12,
    favorited: false,
    retweeted: false,
    lang: 'en' },
  { created_at: 'Thu Jul 19 22:10:56 +0000 2018',
    id: 1020068498909769700,
    id_str: '1020068498909769728',
    text: 'Mein Koinpf https://t.co/yyhigMtet9',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [], urls: [Array] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 17891808,
       id_str: '17891808',
       name: 'Jules Suzdaltsev',
       screen_name: 'jules_su',
       location: 'Los Angeles, CA',
       description: 'mom close the door im doing journalism • EIC at PROMPT • @VICE • fmr: @DISCOVERY @NOWTHISNEWS',
       url: 'https://t.co/MPQPUfK4Qz',
       entities: [Object],
       protected: false,
       followers_count: 72388,
       friends_count: 1751,
       listed_count: 619,
       created_at: 'Fri Dec 05 06:12:10 +0000 2008',
       favourites_count: 33221,
       utc_offset: null,
       time_zone: null,
       geo_enabled: true,
       verified: true,
       statuses_count: 6107,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '131516',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/972653791563735043/NkhFK0AY_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/972653791563735043/NkhFK0AY_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/17891808/1530731260',
       profile_link_color: '000000',
       profile_sidebar_border_color: 'EEEEEE',
       profile_sidebar_fill_color: 'EFEFEF',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: true,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: true,
    quoted_status_id: 1019963458543026200,
    quoted_status_id_str: '1019963458543026178',
    quoted_status:
     { created_at: 'Thu Jul 19 15:13:33 +0000 2018',
       id: 1019963458543026200,
       id_str: '1019963458543026178',
       text: 'Ex-Trump Advisor Steve Bannon Is Making a Cryptocurrency https://t.co/uZQgUJ4pbA https://t.co/8d39d9OVFG',
       truncated: false,
       entities: [Object],
       extended_entities: [Object],
       source: '<a href="https://buffer.com" rel="nofollow">Buffer</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 88,
       favorite_count: 131,
       favorited: false,
       retweeted: false,
       possibly_sensitive: false,
       possibly_sensitive_appealable: false,
       lang: 'en' },
    retweet_count: 48,
    favorite_count: 324,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    possibly_sensitive_appealable: false,
    lang: 'de' },
  { created_at: 'Thu Jul 19 22:09:19 +0000 2018',
    id: 1020068091785429000,
    id_str: '1020068091785428992',
    text: 'RT @eramshaw: Man in office elevator, to me: “Why’s your floor locked down all of the sudden?” \nMe: “After the Maryland newsroom shooting w…',
    truncated: false,
    entities: { hashtags: [], symbols: [], user_mentions: [Array], urls: [] },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user:
     { id: 16877374,
       id_str: '16877374',
       name: 'Matt Novak',
       screen_name: 'paleofuture',
       location: 'Man without a country',
       description: 'Writes the Paleofuture blog for @Gizmodo',
       url: 'https://t.co/kdMVtM3j0X',
       entities: [Object],
       protected: false,
       followers_count: 24115,
       friends_count: 2223,
       listed_count: 1358,
       created_at: 'Mon Oct 20 23:44:16 +0000 2008',
       favourites_count: 9993,
       utc_offset: null,
       time_zone: null,
       geo_enabled: false,
       verified: false,
       statuses_count: 58943,
       lang: 'en',
       contributors_enabled: false,
       is_translator: false,
       is_translation_enabled: false,
       profile_background_color: '131516',
       profile_background_image_url: 'http://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme14/bg.gif',
       profile_background_tile: true,
       profile_image_url: 'http://pbs.twimg.com/profile_images/993928221115670528/lb2GYI6O_normal.jpg',
       profile_image_url_https: 'https://pbs.twimg.com/profile_images/993928221115670528/lb2GYI6O_normal.jpg',
       profile_banner_url: 'https://pbs.twimg.com/profile_banners/16877374/1348212262',
       profile_link_color: '009999',
       profile_sidebar_border_color: 'EEEEEE',
       profile_sidebar_fill_color: 'EFEFEF',
       profile_text_color: '333333',
       profile_use_background_image: true,
       has_extended_profile: false,
       default_profile: false,
       default_profile_image: false,
       following: true,
       follow_request_sent: false,
       notifications: false,
       translator_type: 'none' },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    retweeted_status:
     { created_at: 'Thu Jul 19 15:25:10 +0000 2018',
       id: 1019966382857912300,
       id_str: '1019966382857912320',
       text: 'Man in office elevator, to me: “Why’s your floor locked down all of the sudden?” \nMe: “After the Maryland newsroom… https://t.co/70DkIuKORc',
       truncated: true,
       entities: [Object],
       source: '<a href="https://tapbots.com/software/tweetbot/mac" rel="nofollow">Tweetbot for Mac</a>',
       in_reply_to_status_id: null,
       in_reply_to_status_id_str: null,
       in_reply_to_user_id: null,
       in_reply_to_user_id_str: null,
       in_reply_to_screen_name: null,
       user: [Object],
       geo: null,
       coordinates: null,
       place: null,
       contributors: null,
       is_quote_status: false,
       retweet_count: 479,
       favorite_count: 1215,
       favorited: false,
       retweeted: false,
       lang: 'en' },
    is_quote_status: false,
    retweet_count: 479,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en' } ]
export default jsonResponse;
